--CREATING TABLES--
CREATE TABLE CUSTOMERS (
	CUSTOMER_ID VARCHAR(100) PRIMARY KEY,
	CUSTOMER_UNIQUE_ID VARCHAR(100),
	CUSTOMER_ZIP_CODE_PREFIX INT,
	CUSTOMER_CITY VARCHAR(100),
	CUSTOMER_STATE VARCHAR(50)
);

CREATE TABLE ORDERS (
	ORDER_ID VARCHAR(100) PRIMARY KEY,
	CUSTOMER_ID VARCHAR(100),
	ORDER_STATUS VARCHAR(50),
	ORDER_PURCHASE_TIMESTAMP TIMESTAMP,
	ORDER_APPROVED_AT TIMESTAMP,
	ORDER_DELIVERED_CARRIER_DATE TIMESTAMP,
	ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP,
	ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP
);


CREATE TABLE ORDER_ITEMS (
	ORDER_ID VARCHAR(100),
	ORDER_ITEM_ID INT,
	PRODUCT_ID VARCHAR(100),
	PRICE DECIMAL(10, 2),
	FREIGHT_VALUE DECIMAL(10, 2)
);

CREATE TABLE PRODUCTS (
	PRODUCT_ID VARCHAR(100) PRIMARY KEY,
	PRODUCT_CATEGORY_NAME VARCHAR(100)
);

CREATE TABLE PAYMENTS (
	ORDER_ID VARCHAR(100),
	PAYMENT_TYPE VARCHAR(50),
	PAYMENT_INSTALLMENTS INT,
	PAYMENT_VALUE DECIMAL(10, 2)
);

